import { motion } from "framer-motion";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
// import styles from "@/styles/Home.module.css";

export default function Home() {
	const line1 = "Welcome to";
	const line2 = "EN Portfolio";

	const sentenceVariants = {
		hidden: { opacity: 0 },
		visible: {
			opacity: 1,
			y: 0,
			transition: {
				delay: 0.5,
				staggerChildren: 0.05,
				when: "beforeChildren",
			},
		},
		exit: {
			y: -20,
			opacity: 0,
		},
	};

	const letterVariants = {
		hidden: {
			opacity: 0,
			y: 10,
		},
		visible: {
			opacity: 1,
			y: 0,
		},
	};

	return (
		<>
			<Head>
				<title>EN Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="container h-full font-fontSecondary">
				<div className="flex h-full flex-col items-center justify-center gap-16">
					<motion.h1
						variants={sentenceVariants}
						initial="hidden"
						animate="visible"
						exit="exit"
						className="text-center text-5xl font-black text-clrPrimary md:text-7xl"
					>
						{/* <div>Welcome to</div>
						<div>
							<span className="text-clrAccent">EN</span> Portfolio
						</div> */}
						{line1.split("").map((character, index) => {
							return (
								<motion.span
									key={character + "-" + index}
									variants={letterVariants}
									className={`${character === " " ? "inline" : "inline-block"}`}
								>
									{character}
								</motion.span>
							);
						})}
						<br />
						{line2.split("").map((character, index) => {
							return (
								<motion.span
									key={character + "-" + index}
									variants={letterVariants}
									className={`${character === " " ? "inline" : "inline-block"}`}
								>
									{character}
								</motion.span>
							);
						})}
					</motion.h1>
					<Link href="/about">
						<motion.a
							className="cursor-pointer rounded-full bg-clrSecondary px-10 py-3 text-xl font-bold text-white shadow-sm md:text-3xl"
							initial={{ opacity: 0, scale: 0 }}
							animate={{
								opacity: 1,
								scale: 1,
								y: 0,
								transition: { delay: 1.8 },
							}}
							exit={{ y: -20, opacity: 0 }}
						>
							Let&apos;s Get Started !
						</motion.a>
					</Link>
				</div>
			</div>
		</>
	);
}
